name: deb

on: [push, pull_request]

jobs:
  deb:

    env:
      VERSION: 0.26.0 

    strategy:
      fail-fast: false
      matrix:
        image:
          - buster
          - bullseye
          - bookworm
        os: 
          - ubuntu-latest
          - self-hosted-rpi3
        include:
          - os: ubuntu-latest
            arch: "amd64"
          - os: self-hosted-rpi3
            arch: "armhf"

    runs-on: ${{ matrix.os }}

    container:
      image: debian:${{matrix.image}}

    steps:
    - name: Get dependencies
      run: apt-get update && apt-get install -yq wget debhelper build-essential cmake git rename libatomic1 libasound2-dev libsoxr-dev libvorbisidec-dev libvorbis-dev libflac-dev libopus-dev alsa-utils libpulse-dev libavahi-client-dev avahi-daemon libexpat1-dev
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Checkout tag
      if: ${{ env.VERSION != '0.0.0' }}
      run: git -C $GITHUB_WORKSPACE/src/snapcast/ checkout v${{ env.VERSION }}
    - name: Setup environment
      run: |
        echo "SHA=$(git -C $GITHUB_WORKSPACE/src/snapcast rev-parse HEAD)" >> $GITHUB_ENV
        echo "PARENT_DIR=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
    - name: Clean up
      run: rm -rf ${{env.PARENT_DIR}}/snap*_${{ matrix.arch }}.deb
    - name: Cache boost
      id: cache-boost
      uses: actions/cache@v2
      with:
        path: boost_1_78_0
        key: ${{ runner.os }}-boost
    - name: Get boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: wget https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.bz2 && tar xjf boost_1_78_0.tar.bz2
    - name: Create deb package
      run: |
        fakeroot make -f debian/rules CMAKEFLAGS="-DBOOST_ROOT=$GITHUB_WORKSPACE/boost_1_78_0 -DCMAKE_BUILD_TYPE:STRING=Release -DREVISION=${{ env.SHA }} -DCMAKE_CXX_FLAGS=-DJSON_HAS_CPP_14 -DBUILD_WITH_PULSE=OFF" binary
        rename 's/_${{ matrix.arch }}/_without-pulse_${{ matrix.arch }}/g' ../snapclient*_${{ matrix.arch }}.deb
        fakeroot make -f debian/rules clean
        fakeroot make -f debian/rules CMAKEFLAGS="-DBOOST_ROOT=$GITHUB_WORKSPACE/boost_1_78_0 -DCMAKE_BUILD_TYPE:STRING=Release -DREVISION=${{ env.SHA }} -DCMAKE_CXX_FLAGS=-DJSON_HAS_CPP_14" binary
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: snapcast_${{ matrix.arch }}-debian-${{matrix.image}}-${{env.SHA}}
        path: ${{env.PARENT_DIR}}/snap*_${{ matrix.arch }}.deb
